using Compendium.Database;
using Compendium.Models.CoreData;
using Compendium.Models.CoreData.Enums;

namespace Compendium.Provider
{
    public class WeaponTypeProvider : Provider<WeaponType>
    {
        public WeaponTypeProvider(IDatabaseConnection db) : base(db)
        {
            EnsureDefaults();
        }

        private void EnsureDefaults()
        {
            foreach (var def in GetDefaultValues())
                Store(def);
        }

        private IEnumerable<WeaponType> GetDefaultValues()
        {
            return new[]
            {
                new WeaponType(WeaponCategory.SimpleMeleeWeapon, "Club",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target"},
                    new HitEffect {DamageType = DamageType.Bludgeoning, DamageDie = new DieRoll(4, 1, 0)},
                    new []{"Light"}),
                new WeaponType(WeaponCategory.SimpleMeleeWeapon, "Dagger",
                    new Attack() { Type = AttackType.Melee_or_Ranged_Weapon_Attack, Reach = 5, ShortRange = 20, LongRange = 60, Target="one target"},
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(4, 1, 0) },
                    new[] { "Finesse", "Light", "Throw" }),
                new WeaponType(WeaponCategory.SimpleMeleeWeapon, "Greatclub",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Bludgeoning, DamageDie = new DieRoll(8, 1, 0) },
                    new[] { "Two-handed" }),
                new WeaponType(WeaponCategory.SimpleMeleeWeapon, "Handaxe",
                    new Attack() { Type = AttackType.Melee_or_Ranged_Weapon_Attack, Reach = 5, ShortRange = 20, LongRange = 60,Target="one target" },
                    new HitEffect { DamageType = DamageType.Slashing, DamageDie = new DieRoll(6, 1, 0) },
                    new[] { "Light", "Throw" }),
                new WeaponType(WeaponCategory.SimpleMeleeWeapon, "Javelin",
                    new Attack() { Type = AttackType.Melee_or_Ranged_Weapon_Attack, Reach = 5, ShortRange = 30, LongRange = 120, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(6, 1, 0) },
                    new[] { "Throw" }),
                new WeaponType(WeaponCategory.SimpleMeleeWeapon, "Light hammer",
                    new Attack() { Type = AttackType.Melee_or_Ranged_Weapon_Attack, Reach = 5, ShortRange = 20, LongRange = 60, Target="one target" },
                    new HitEffect { DamageType = DamageType.Bludgeoning, DamageDie = new DieRoll(6, 1, 0) },
                    new[] { "Light", "Throw" }),
                new WeaponType(WeaponCategory.SimpleMeleeWeapon, "Mace",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Bludgeoning, DamageDie = new DieRoll(6, 1, 0) },
                    new string[] { }),
                new WeaponType(WeaponCategory.SimpleMeleeWeapon, "Quarterstaff",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Bludgeoning, DamageDie = new DieRoll(6, 1, 0) },
                    new[] { "Versatile" }),
                new WeaponType(WeaponCategory.SimpleMeleeWeapon, "Sickle",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Slashing, DamageDie = new DieRoll(4, 1, 0) },
                    new[] { "Light" }),
                new WeaponType(WeaponCategory.SimpleMeleeWeapon, "Spear",
                    new Attack() { Type = AttackType.Melee_or_Ranged_Weapon_Attack, Reach = 5, ShortRange = 20, LongRange = 60, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(6, 1, 0) },
                    new[] { "Versatile", "Throw" }),
                new WeaponType(WeaponCategory.SimpleRangedWeapon, "Crossbow, light",
                    new Attack() { Type = AttackType.Ranged_Weapon_Attack, ShortRange = 80, LongRange = 320, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(8, 1, 0) },
                    new[] { "Ammunition", "Loading", "Two-handed" }),
                new WeaponType(WeaponCategory.SimpleRangedWeapon, "Dart",
                    new Attack() { Type = AttackType.Ranged_Weapon_Attack, ShortRange = 20, LongRange = 60, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(4, 1, 0) },
                    new[] { "Finesse", "Throw" }),
                new WeaponType(WeaponCategory.SimpleRangedWeapon, "Shortbow",
                    new Attack() { Type = AttackType.Ranged_Weapon_Attack, ShortRange = 80, LongRange = 320, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(6, 1, 0) },
                    new[] { "Ammunition", "Two-handed" }),
                new WeaponType(WeaponCategory.SimpleRangedWeapon, "Sling",
                    new Attack() { Type = AttackType.Ranged_Weapon_Attack, ShortRange = 30, LongRange = 120, Target="one target" },
                    new HitEffect { DamageType = DamageType.Bludgeoning, DamageDie = new DieRoll(6, 1, 0) },
                    new[] { "Ammunition" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Battleaxe",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Slashing, DamageDie = new DieRoll(8, 1, 0) },
                    new[] { "Versatile" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Flail",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Bludgeoning, DamageDie = new DieRoll(8, 1, 0) },
                    new string[] { }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Glaive",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 10, Target="one target" },
                    new HitEffect { DamageType = DamageType.Slashing, DamageDie = new DieRoll(10, 1, 0) },
                    new[] { "Heavy", "Reach", "Two-handed" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Greataxe",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Slashing, DamageDie = new DieRoll(12, 1, 0) },
                    new[] { "Heavy", "Two-handed" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Greatsword",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Slashing, DamageDie = new DieRoll(6, 2, 0) },
                    new[] { "Heavy", "Two-handed" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Halberd",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 10, Target="one target" },
                    new HitEffect { DamageType = DamageType.Slashing, DamageDie = new DieRoll(10, 1, 0) },
                    new[] { "Heavy", "Reach", "Two-handed" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Lance", //TODO: Special
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 10, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(12, 1, 0) },
                    new[] { "Special", "Reach" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Longsword",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Slashing, DamageDie = new DieRoll(8, 1, 0) },
                    new[] { "Versatile" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Maul",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Slashing, DamageDie = new DieRoll(6, 2, 0) },
                    new[] { "Heavy", "Two-handed" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Morningstar",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(8, 1, 0) },
                    new string[] { }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Pike",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 10, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(10, 1, 0) },
                    new[] { "Heavy", "Reach", "Two-handed" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Rapier",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(8, 1, 0) },
                    new[] { "Finesse" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Scimitar",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Slashing, DamageDie = new DieRoll(6, 1, 0) },
                    new[] { "Finesse", "Light" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Shortsword",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(6, 1, 0) },
                    new[] { "Finesse", "Light" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Trident",
                    new Attack() { Type = AttackType.Melee_or_Ranged_Weapon_Attack, Reach = 5, ShortRange = 20, LongRange = 60, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(6, 1, 0) },
                    new[] { "Versatile", "Throw" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "War pick",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(8, 1, 0) },
                    new string[] { }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Warhammer",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Bludgeoning, DamageDie = new DieRoll(8, 1, 0) },
                    new[] { "Versatile" }),
                new WeaponType(WeaponCategory.MartialMeleeWeapon, "Whip",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 10, Target="one target" },
                    new HitEffect { DamageType = DamageType.Slashing, DamageDie = new DieRoll(4, 1, 0) },
                    new[] { "Finesse", "Reach" }),
                new WeaponType(WeaponCategory.MartialRangedWeapon, "Blowgun",
                    new Attack() { Type = AttackType.Ranged_Weapon_Attack, ShortRange = 25, LongRange = 100, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(0, 0, 1) },
                    new[] { "Ammunition", "Loading" }),
                new WeaponType(WeaponCategory.MartialRangedWeapon, "Crossbow, hand",
                    new Attack() { Type = AttackType.Ranged_Weapon_Attack, ShortRange = 30, LongRange = 120, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(6, 1, 0) },
                    new[] { "Ammunition", "Loading", "Light" }),
                new WeaponType(WeaponCategory.MartialRangedWeapon, "Crossbow, heavy",
                    new Attack() { Type = AttackType.Ranged_Weapon_Attack, ShortRange = 100, LongRange = 400, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(10, 1, 0) },
                    new[] { "Ammunition", "Loading", "Two-handed", "Heavy" }),
                new WeaponType(WeaponCategory.MartialRangedWeapon, "Longbow",
                    new Attack() { Type = AttackType.Ranged_Weapon_Attack, ShortRange = 150, LongRange = 600, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(8, 1, 0) },
                    new[] { "Ammunition", "Two-handed", "Heavy" }),
                new WeaponType(WeaponCategory.MartialRangedWeapon, "Net",
                    new Attack() { Type = AttackType.Ranged_Weapon_Attack, ShortRange = 5, LongRange = 15, Target="one target" },
                    new HitEffect { Condition = new List<Condition>() { Condition.Restrained } },
                    new[] { "Special", "Throw" }),
                new WeaponType(WeaponCategory.Body, "Claw",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target"},
                    new HitEffect { DamageType = DamageType.Slashing, DamageDie = new DieRoll(6, 1, 0) },
                    new string[] { }),
                new WeaponType(WeaponCategory.Body, "Bite",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(8, 1, 0) },
                    new string[] { }),
                new WeaponType(WeaponCategory.Body, "Tail",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 5, Target="one target" },
                    new HitEffect { DamageType = DamageType.Bludgeoning, DamageDie = new DieRoll(8, 1, 0) },
                    new string[] { }),
                new WeaponType(WeaponCategory.Body, "Tentacle",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 10, Target="one target" },
                    new HitEffect { DamageType = DamageType.Bludgeoning, DamageDie = new DieRoll(8, 1, 0) },
                    new string[] { }),
                new WeaponType(WeaponCategory.Body, "Fist",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 10, Target="one target" },
                    new HitEffect { DamageType = DamageType.Bludgeoning, DamageDie = new DieRoll(8, 1, 0) },
                    new string[] { }),
                new WeaponType(WeaponCategory.Body, "Pincer",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 10, Target="one target" },
                    new HitEffect { DamageType = DamageType.Bludgeoning, DamageDie = new DieRoll(8, 1, 0) },
                    new string[] { }),
                new WeaponType(WeaponCategory.Body, "Hoof",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 10, Target="one target" },
                    new HitEffect { DamageType = DamageType.Slashing, DamageDie = new DieRoll(8, 1, 0) },
                    new string[] { }),
                new WeaponType(WeaponCategory.Body, "Gore",
                    new Attack() { Type = AttackType.Melee_Weapon_Attack, Reach = 10, Target="one target" },
                    new HitEffect { DamageType = DamageType.Piercing, DamageDie = new DieRoll(10, 1, 0) },
                    new string[] { }),
            };
        }
    }
}
